apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: testapp
  namespace: testapp
spec:
  suspend: false
  values:
    image:
      tag: hub.test.io/app:v1.17b # {"$imagepolicy": "testapp:testapp:tag"}
    replicaCount: 4
    livenessProbe:
      httpGet:
        path: /
        port: http
      periodSeconds: 10
      timeoutSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: http
      periodSeconds: 10
      timeoutSeconds: 10
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80


