---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: testapp-chart
  namespace: testapp
spec:
  url: ssh://testrepo-with-chart/app.git
  interval: 5m0s
  ref:
    branch: master
  secretRef:
    name: testapp-git-auth
  ignore: |
    # exclude all
    /*
    # include chart directory
    !/app_v1 

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: testapp
  namespace: testapp
spec:
  interval: 5m
  chart:
    spec:
      chart: ./app_v1
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: testapp-chart
        namespace: testapp
